# M18.69-RAM-FIX (wie Mnemon): 3-GB-Container → OOM-Kill vermeiden.
org.gradle.jvmargs=-Xmx1024m -Dfile.encoding=UTF-8 -XX:+UseSerialGC -XX:MaxMetaspaceSize=384m
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.workers.max=1
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kapt.use.worker.api=false
